
import { InventoryItem, User } from './types';

export const INITIAL_USERS: User[] = [
  { id: 'admin', username: 'Admin', password: 'admin123', role: 'ADMIN', displayName: 'Administrador Sistema' },
  { id: 'almacen', username: 'Almacen', password: 'almacen123', role: 'ALMACEN', displayName: 'Bodega Central' },
  ...Array.from({ length: 30 }, (_, i) => ({
    id: `movil-${i + 1}`,
    username: `Movil-${i + 1}`,
    password: `movil-${i + 1}`,
    role: 'MOBILE' as const,
    displayName: `Ambulancia Móvil ${i + 1}`
  })),
  ...Array.from({ length: 30 }, (_, i) => ({
    id: `cond-movil-${i + 1}`,
    username: `CONDMOVIL-${i + 1}`,
    password: `CONDMOVIL-${i + 1}`,
    role: 'MOBILE' as const,
    displayName: `Conductor Móvil ${i + 1}`
  }))
];

export const DRIVER_CATEGORIES = [
  "LUCES",
  "CABINA",
  "LÍQUIDOS",
  "MOTOR",
  "LLANTAS",
  "EQUIPOS DE PREVENCIÓN Y SEGURIDAD"
];

export const DRIVER_ITEMS: InventoryItem[] = [
  // LUCES (Página 1 PDF)
  { id: 'luz-1', category: 'LUCES', name: 'Luces Tablero de Instrumentos', requiredStock: 'Funcional', type: 'INSUMO' },
  { id: 'luz-2', category: 'LUCES', name: 'Direccionales Delanteras', requiredStock: 'Funcional', type: 'INSUMO' },
  { id: 'luz-3', category: 'LUCES', name: 'Direccionales Traseras', requiredStock: 'Funcional', type: 'INSUMO' },
  { id: 'luz-4', category: 'LUCES', name: 'Luces Estacionarias de Parqueo', requiredStock: 'Funcional', type: 'INSUMO' },
  { id: 'luz-5', category: 'LUCES', name: 'Luces Frontales Altas/Bajas', requiredStock: 'Funcional', type: 'INSUMO' },
  { id: 'luz-6', category: 'LUCES', name: 'Barra Luces Emergencia Delantera', requiredStock: 'Funcional', type: 'INSUMO' },
  { id: 'luz-7', category: 'LUCES', name: 'Barra Luces Emergencia Trasera', requiredStock: 'Funcional', type: 'INSUMO' },
  { id: 'luz-8', category: 'LUCES', name: 'Luces Rojas Laterales Emergencia', requiredStock: 'Funcional', type: 'INSUMO' },
  { id: 'luz-9', category: 'LUCES', name: 'Luces Blancas Laterales Emergencia', requiredStock: 'Funcional', type: 'INSUMO' },
  { id: 'luz-10', category: 'LUCES', name: 'Luces de Reversa', requiredStock: 'Funcional', type: 'INSUMO' },
  { id: 'luz-11', category: 'LUCES', name: 'Luz Trasera Blanca (Esploradora)', requiredStock: 'Funcional', type: 'INSUMO' },
  { id: 'luz-12', category: 'LUCES', name: 'Exploradoras Delanteras', requiredStock: 'Funcional', type: 'INSUMO' },

  // CABINA (Página 1 y 2 PDF)
  { id: 'cab-1', category: 'CABINA', name: 'Aire Acondicionado', requiredStock: 'Funcional', type: 'INSUMO' },
  { id: 'cab-2', category: 'CABINA', name: 'Pito', requiredStock: 'Funcional', type: 'INSUMO' },
  { id: 'cab-3', category: 'CABINA', name: 'Alarma de Reversa', requiredStock: 'Funcional', type: 'INSUMO' },
  { id: 'cab-4', category: 'CABINA', name: 'Cinturón de Seguridad Conductor', requiredStock: 'Funcional', type: 'INSUMO' },
  { id: 'cab-5', category: 'CABINA', name: 'Cinturón de Seguridad Silla Copiloto', requiredStock: 'Funcional', type: 'INSUMO' },
  { id: 'cab-6', category: 'CABINA', name: 'Encendido del Vehículo', requiredStock: 'Funcional', type: 'INSUMO' },
  { id: 'cab-7', category: 'CABINA', name: 'Espejo Retrovisor Interno', requiredStock: 'Óptimo', type: 'INSUMO' },
  { id: 'cab-8', category: 'CABINA', name: 'Cámara de Reversa', requiredStock: 'Funcional', type: 'INSUMO' },
  { id: 'cab-9', category: 'CABINA', name: 'Revisión Pedal del Freno', requiredStock: 'Funcional', type: 'INSUMO' },
  { id: 'cab-10', category: 'CABINA', name: 'Revisión Freno de Mano', requiredStock: 'Funcional', type: 'INSUMO' },
  { id: 'cab-11', category: 'CABINA', name: 'Estado de Plumillas', requiredStock: 'Funcional', type: 'INSUMO' },
  { id: 'cab-12', category: 'CABINA', name: 'Estado Puerta Lateral Derecha', requiredStock: 'Óptimo', type: 'INSUMO' },
  { id: 'cab-13', category: 'CABINA', name: 'Estado Puerta Lateral Izquierda', requiredStock: 'Óptimo', type: 'INSUMO' },
  { id: 'cab-14', category: 'CABINA', name: 'Estado Panorámico', requiredStock: 'Óptimo', type: 'INSUMO' },
  { id: 'cab-15', category: 'CABINA', name: 'Vidrios y Cremalleras Puertas', requiredStock: 'Funcional', type: 'INSUMO' },
  { id: 'cab-16', category: 'CABINA', name: 'Espejo Lateral Derecho', requiredStock: 'Óptimo', type: 'INSUMO' },
  { id: 'cab-17', category: 'CABINA', name: 'Espejo Lateral Izquierdo', requiredStock: 'Óptimo', type: 'INSUMO' },
  { id: 'cab-18', category: 'CABINA', name: 'Estado Bomper Delantero/Trasero', requiredStock: 'Óptimo', type: 'INSUMO' },
  { id: 'cab-19', category: 'CABINA', name: 'Estado Capot', requiredStock: 'Óptimo', type: 'INSUMO' },
  { id: 'cab-20', category: 'CABINA', name: 'Estado Techo Cabina (Ext/Int)', requiredStock: 'Óptimo', type: 'INSUMO' },
  { id: 'cab-21', category: 'CABINA', name: 'Estado Cojinería Sillas', requiredStock: 'Óptimo', type: 'INSUMO' },
  { id: 'cab-22', category: 'CABINA', name: 'Sirena (3 tonos + Perifoneo)', requiredStock: 'Funcional', type: 'INSUMO' },
  { id: 'cab-23', category: 'CABINA', name: 'Radio Comunicación CRUE', requiredStock: 'Funcional', type: 'INSUMO' },
  { id: 'cab-24', category: 'CABINA', name: 'Radio AM/FM', requiredStock: 'Funcional', type: 'INSUMO' },

  // LÍQUIDOS (Página 2 y 3 PDF)
  { id: 'liq-1', category: 'LÍQUIDOS', name: 'Nivel Líquido de Embrague', requiredStock: 'Óptimo', type: 'INSUMO' },
  { id: 'liq-2', category: 'LÍQUIDOS', name: 'Nivel Líquido Limpiaparabrisas', requiredStock: 'Óptimo', type: 'INSUMO' },
  { id: 'liq-3', category: 'LÍQUIDOS', name: 'Nivel Líquido de Frenos', requiredStock: 'Óptimo', type: 'INSUMO' },
  { id: 'liq-4', category: 'LÍQUIDOS', name: 'Nivel Refrigerante / Agua', requiredStock: 'Óptimo', type: 'INSUMO' },
  { id: 'liq-5', category: 'LÍQUIDOS', name: 'Nivel Aceite del Motor', requiredStock: 'Óptimo', type: 'INSUMO' },

  // MOTOR (Página 3 PDF)
  { id: 'mot-1', category: 'MOTOR', name: 'Estado General del Motor', requiredStock: 'Óptimo', type: 'INSUMO' },
  { id: 'mot-2', category: 'MOTOR', name: 'Estado de Correas', requiredStock: 'Óptimo', type: 'INSUMO' },
  { id: 'mot-3', category: 'MOTOR', name: 'Caja de Velocidades', requiredStock: 'Funcional', type: 'INSUMO' },
  { id: 'mot-4', category: 'MOTOR', name: 'Alternador', requiredStock: 'Funcional', type: 'INSUMO' },
  { id: 'mot-5', category: 'MOTOR', name: 'Batería del Vehículo', requiredStock: 'Óptimo', type: 'INSUMO' },
  { id: 'mot-6', category: 'MOTOR', name: 'Batería Habitáculo Médico', requiredStock: 'Óptimo', type: 'INSUMO' },

  // LLANTAS (Página 3 PDF)
  { id: 'lla-1', category: 'LLANTAS', name: 'Llantas Delanteras', requiredStock: 'Óptimo', type: 'INSUMO' },
  { id: 'lla-2', category: 'LLANTAS', name: 'Llantas Traseras', requiredStock: 'Óptimo', type: 'INSUMO' },
  { id: 'lla-3', category: 'LLANTAS', name: 'Llanta de Repuesto', requiredStock: 'Óptimo', type: 'INSUMO' },

  // EQUIPOS DE PREVENCIÓN Y SEGURIDAD (Página 3 y 4 PDF)
  { id: 'seg-1', category: 'EQUIPOS DE PREVENCIÓN Y SEGURIDAD', name: 'Chalecos Reflectivos (2-3)', requiredStock: 'Óptimo', type: 'INSUMO' },
  { id: 'seg-2', category: 'EQUIPOS DE PREVENCIÓN Y SEGURIDAD', name: 'Conos / Triángulos Reflectivos (min 2)', requiredStock: 2, type: 'DISPOSITIVO' },
  { id: 'seg-3', category: 'EQUIPOS DE PREVENCIÓN Y SEGURIDAD', name: 'Cruceta / Llave de Pernos', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'seg-4', category: 'EQUIPOS DE PREVENCIÓN Y SEGURIDAD', name: 'Varilla Gato / Repuesto', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'seg-5', category: 'EQUIPOS DE PREVENCIÓN Y SEGURIDAD', name: 'Linterna de Mano', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'seg-6', category: 'EQUIPOS DE PREVENCIÓN Y SEGURIDAD', name: 'Alicate', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'seg-7', category: 'EQUIPOS DE PREVENCIÓN Y SEGURIDAD', name: 'Juego Destornilladores (Pala/Estrella)', requiredStock: 6, type: 'DISPOSITIVO' },
  { id: 'seg-8', category: 'EQUIPOS DE PREVENCIÓN Y SEGURIDAD', name: 'Martillo', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'seg-9', category: 'EQUIPOS DE PREVENCIÓN Y SEGURIDAD', name: 'Llave Expansiva', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'seg-10', category: 'EQUIPOS DE PREVENCIÓN Y SEGURIDAD', name: 'Juego Llaves Boca Fijas', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'seg-11', category: 'EQUIPOS DE PREVENCIÓN Y SEGURIDAD', name: 'Palanca Patecabra', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'seg-12', category: 'EQUIPOS DE PREVENCIÓN Y SEGURIDAD', name: 'Extintores ABC 2.26KG (Cab/Hab)', requiredStock: 2, type: 'DISPOSITIVO' },
  { id: 'seg-13', category: 'EQUIPOS DE PREVENCIÓN Y SEGURIDAD', name: 'Gato Hidráulico / Mecánico', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'seg-14', category: 'EQUIPOS DE PREVENCIÓN Y SEGURIDAD', name: 'Tacos de Madera / Plástico (2)', requiredStock: 2, type: 'INSUMO' },
  { id: 'seg-15', category: 'EQUIPOS DE PREVENCIÓN Y SEGURIDAD', name: 'Cables Iniciación Eléctrica', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'seg-16', category: 'EQUIPOS DE PREVENCIÓN Y SEGURIDAD', name: 'Cuerda con Ganchos Tracción (30m)', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'seg-17', category: 'EQUIPOS DE PREVENCIÓN Y SEGURIDAD', name: 'Cable Extensión Eléctrica (30m)', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'seg-18', category: 'EQUIPOS DE PREVENCIÓN Y SEGURIDAD', name: 'Lámpara Busca Direcciones', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'seg-19', category: 'EQUIPOS DE PREVENCIÓN Y SEGURIDAD', name: 'Guantes de Carnaza', requiredStock: 1, type: 'INSUMO' },
  { id: 'seg-20', category: 'EQUIPOS DE PREVENCIÓN Y SEGURIDAD', name: 'Zisaya (Pinza Cortatodo)', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'seg-21', category: 'EQUIPOS DE PREVENCIÓN Y SEGURIDAD', name: 'Rollo Cinta Aislante', requiredStock: 1, type: 'INSUMO' },
  { id: 'seg-22', category: 'EQUIPOS DE PREVENCIÓN Y SEGURIDAD', name: 'Caja de Fusibles Surtidos', requiredStock: 1, type: 'INSUMO' }
];

export const CATEGORIES = [
  "RESPIRATORIO", 
  "OXIGENO", 
  "CIRCULATORIO", 
  "MEDICAMENTOS",
  "KIT COVID", 
  "OTROS DISPOSITIVOS", 
  "TRAUMA", 
  "ASEO",
  "EQUIPOS BIOMEDICOS", 
  "KIT DE DERRAMES (PARA FLUIDOS CORPORALES)", 
  "KIT DE ATAQUE POR AGENTES QUIMICOS", 
  "KIT ATENCIÓN DE PARTOS"
];

export const INVENTORY_ITEMS: InventoryItem[] = [
  // RESPIRATORIO
  { id: 'res-1', category: 'RESPIRATORIO', name: 'BVM Adulto', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'res-2', category: 'RESPIRATORIO', name: 'Canula Nasal Adulto', requiredStock: 2, type: 'DISPOSITIVO' },
  { id: 'res-3', category: 'RESPIRATORIO', name: 'Máscara de Oxígeno Adulto', requiredStock: 2, type: 'DISPOSITIVO' },
  { id: 'res-4', category: 'RESPIRATORIO', name: 'Máscara con Reservorio Adulto', requiredStock: 2, type: 'DISPOSITIVO' },
  { id: 'res-5', category: 'RESPIRATORIO', name: 'Equipo Micro-Nebulización Adulto', requiredStock: 2, type: 'DISPOSITIVO' },
  { id: 'res-6', category: 'RESPIRATORIO', name: 'Equipo Ventury Adulto', requiredStock: 2, type: 'DISPOSITIVO' },
  { id: 'res-7', category: 'RESPIRATORIO', name: 'Máscara Laríngea / Aditamento Supraglótico Adulto Varios Tamaños', requiredStock: 3, type: 'DISPOSITIVO' },
  { id: 'res-8', category: 'RESPIRATORIO', name: 'BVM Pediátrico', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'res-9', category: 'RESPIRATORIO', name: 'Cánula Nasal Pediátrica', requiredStock: 2, type: 'DISPOSITIVO' },
  { id: 'res-10', category: 'RESPIRATORIO', name: 'Máscara de Oxígeno Pediátrica', requiredStock: 2, type: 'DISPOSITIVO' },
  { id: 'res-11', category: 'RESPIRATORIO', name: 'Máscara con Reservorio Pediátrica', requiredStock: 2, type: 'DISPOSITIVO' },
  { id: 'res-12', category: 'RESPIRATORIO', name: 'Equipo Micro-Nebulización Pediátrico', requiredStock: 2, type: 'DISPOSITIVO' },
  { id: 'res-13', category: 'RESPIRATORIO', name: 'Equipo Ventury Pediátrico', requiredStock: 2, type: 'DISPOSITIVO' },
  { id: 'res-14', category: 'RESPIRATORIO', name: 'Máscara Laríngea / Aditamento Supraglótico Pediátrico Varios Tamaños', requiredStock: 3, type: 'DISPOSITIVO' },
  { id: 'res-15', category: 'RESPIRATORIO', name: 'Cánulas de Guedel / Mayo (Diferentes Tamaños)', requiredStock: 6, type: 'DISPOSITIVO' },
  { id: 'res-16', category: 'RESPIRATORIO', name: 'Extencion de oxigeno', requiredStock: 2, type: 'DISPOSITIVO' },

  // OXIGENO
  { id: 'oxi-1', category: 'OXIGENO', name: 'Bala Central De 3M', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'oxi-2', category: 'OXIGENO', name: 'Bala Portátil De 1M', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'oxi-3', category: 'OXIGENO', name: 'Manómetro Central', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'oxi-4', category: 'OXIGENO', name: 'Manómetro Portátil', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'oxi-5', category: 'OXIGENO', name: 'Flujómetro', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'oxi-6', category: 'OXIGENO', name: 'Humidificador Simple', requiredStock: 2, type: 'DISPOSITIVO' },
  { id: 'oxi-7', category: 'OXIGENO', name: 'Humidificador Véntury', requiredStock: 2, type: 'DISPOSITIVO' },
  { id: 'oxi-8', category: 'OXIGENO', name: 'Rácor', requiredStock: 4, type: 'DISPOSITIVO' },

  // CIRCULATORIO
  { id: 'cir-1', category: 'CIRCULATORIO', name: 'Jelco / Cateter Venoso # 14', requiredStock: 3, type: 'DISPOSITIVO' },
  { id: 'cir-2', category: 'CIRCULATORIO', name: 'Jelco / Cateter Venoso # 16', requiredStock: 3, type: 'DISPOSITIVO' },
  { id: 'cir-3', category: 'CIRCULATORIO', name: 'Jelco / Cateter Venoso # 18', requiredStock: 3, type: 'DISPOSITIVO' },
  { id: 'cir-4', category: 'CIRCULATORIO', name: 'Jelco / Cateter Venoso # 20', requiredStock: 3, type: 'DISPOSITIVO' },
  { id: 'cir-5', category: 'CIRCULATORIO', name: 'Jelco / Cateter Venoso # 22', requiredStock: 3, type: 'DISPOSITIVO' },
  { id: 'cir-6', category: 'CIRCULATORIO', name: 'Equipo Pericraneal Diferentes Tamaños', requiredStock: 2, type: 'DISPOSITIVO' },
  { id: 'cir-7', category: 'CIRCULATORIO', name: 'Equipo Venoclisis Macrogoteo', requiredStock: 6, type: 'DISPOSITIVO' },
  { id: 'cir-8', category: 'CIRCULATORIO', name: 'Equipo Venoclisis Microgoteo', requiredStock: 3, type: 'DISPOSITIVO' },
  { id: 'cir-9', category: 'CIRCULATORIO', name: 'Torniquete De Hemorragias Grado Militar', requiredStock: 2, type: 'DISPOSITIVO' },
  { id: 'cir-10', category: 'CIRCULATORIO', name: 'Torniquete simple', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'cir-11', category: 'CIRCULATORIO', name: 'Jeringa Desechable 1 ML', requiredStock: 3, type: 'DISPOSITIVO' },
  { id: 'cir-12', category: 'CIRCULATORIO', name: 'Jeringa Desechable 3 ML', requiredStock: 3, type: 'DISPOSITIVO' },
  { id: 'cir-13', category: 'CIRCULATORIO', name: 'Jeringa Desechable 5 ML', requiredStock: 3, type: 'DISPOSITIVO' },
  { id: 'cir-14', category: 'CIRCULATORIO', name: 'Jeringa Desechable 10 ML', requiredStock: 3, type: 'DISPOSITIVO' },
  { id: 'cir-15', category: 'CIRCULATORIO', name: 'Jeringa Desechable 20 ML', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'cir-16', category: 'CIRCULATORIO', name: 'Jeringa Desechable 50 ML', requiredStock: 2, type: 'DISPOSITIVO' },

  // MEDICAMENTOS
  { id: 'med-1', category: 'MEDICAMENTOS', name: 'Solucion Salina Natural 0,9% x 500 ML', requiredStock: 6, type: 'MEDICAMENTO' },
  { id: 'med-2', category: 'MEDICAMENTOS', name: 'Lactato de Ringer-Soluc.Harttmann x 500ML', requiredStock: 4, type: 'MEDICAMENTO' },
  { id: 'med-3', category: 'MEDICAMENTOS', name: 'Dextrosa en Agua Destilada DAD 5%x500 ML', requiredStock: 2, type: 'MEDICAMENTO' },
  { id: 'med-4', category: 'MEDICAMENTOS', name: 'Dextrosa en Agua Destilada DAD10%x500ML', requiredStock: 1, type: 'MEDICAMENTO' },

  // KIT COVID
  { id: 'cov-1', category: 'KIT COVID', name: 'Kit Bioseguridad y/o Bioprotección (camisa, pantalon, gorro, polainas)', requiredStock: 2, type: 'INSUMO' },
  { id: 'cov-2', category: 'KIT COVID', name: 'Monogafas', requiredStock: 2, type: 'INSUMO' },
  { id: 'cov-3', category: 'KIT COVID', name: 'Guantes Estériles', requiredStock: 2, type: 'DISPOSITIVO' },
  { id: 'cov-4', category: 'KIT COVID', name: 'Tapabocas N 95', requiredStock: 2, type: 'INSUMO' },

  // OTROS DISPOSITIVOS
  { id: 'otr-1', category: 'OTROS DISPOSITIVOS', name: 'Manguera de succion', requiredStock: 2, type: 'DISPOSITIVO' },
  { id: 'otr-2', category: 'OTROS DISPOSITIVOS', name: 'Sonda de Succión varios tamaños', requiredStock: 3, type: 'DISPOSITIVO' },
  { id: 'otr-3', category: 'OTROS DISPOSITIVOS', name: 'Algodón (Torundas)', requiredStock: 30, type: 'DISPOSITIVO' },
  { id: 'otr-4', category: 'OTROS DISPOSITIVOS', name: 'Gasas Esteril Pre-cortada', requiredStock: 10, type: 'DISPOSITIVO' },
  { id: 'otr-5', category: 'OTROS DISPOSITIVOS', name: 'Micropore (Rollo)', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'otr-6', category: 'OTROS DISPOSITIVOS', name: 'Esparadrapo (Rollo)', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'otr-7', category: 'OTROS DISPOSITIVOS', name: 'Manta Termica', requiredStock: 1, type: 'INSUMO' },
  { id: 'otr-8', category: 'OTROS DISPOSITIVOS', name: 'Tijeras de trauma', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'otr-9', category: 'OTROS DISPOSITIVOS', name: 'Frasco de Alcohol Antiseptico', requiredStock: 1, type: 'INSUMO' },
  { id: 'otr-10', category: 'OTROS DISPOSITIVOS', name: 'Isodine Espuma (Jabon Yodado Desinfectante)', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'otr-11', category: 'OTROS DISPOSITIVOS', name: 'Isodine Solución (Solución Yodada Desinfectante)', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'otr-12', category: 'OTROS DISPOSITIVOS', name: 'Gel Antibacterial', requiredStock: 1, type: 'INSUMO' },
  { id: 'otr-13', category: 'OTROS DISPOSITIVOS', name: 'Jabón Clorexidina Antibacterial 4%', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'otr-14', category: 'OTROS DISPOSITIVOS', name: 'Papel Higiénico (Rollo)', requiredStock: 1, type: 'INSUMO' },
  { id: 'otr-15', category: 'OTROS DISPOSITIVOS', name: 'Toallas Sanitarias Paquete x 10 Toallas', requiredStock: 1, type: 'INSUMO' },
  { id: 'otr-16', category: 'OTROS DISPOSITIVOS', name: 'Tapabocas de Manejo', requiredStock: 10, type: 'DISPOSITIVO' },
  { id: 'otr-17', category: 'OTROS DISPOSITIVOS', name: 'Tapabocas Específico N95', requiredStock: 2, type: 'INSUMO' },
  { id: 'otr-18', category: 'OTROS DISPOSITIVOS', name: 'Cobija para Paciente', requiredStock: 1, type: 'INSUMO' },
  { id: 'otr-19', category: 'OTROS DISPOSITIVOS', name: 'Sábanas Desechables para Camilla', requiredStock: 3, type: 'INSUMO' },
  { id: 'otr-20', category: 'OTROS DISPOSITIVOS', name: 'Camilla', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'otr-21', category: 'OTROS DISPOSITIVOS', name: 'Tabla Espinal Larga Con Araña', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'otr-22', category: 'OTROS DISPOSITIVOS', name: 'Tabla Espinal Corta Con Araña', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'otr-23', category: 'OTROS DISPOSITIVOS', name: 'Guardian Cortopunzantes', requiredStock: 1, type: 'INSUMO' },
  { id: 'otr-24', category: 'OTROS DISPOSITIVOS', name: 'Caneca Roja (Patógenos)', requiredStock: 1, type: 'INSUMO' },
  { id: 'otr-25', category: 'OTROS DISPOSITIVOS', name: 'Caneca Negra (Ordinarios)', requiredStock: 1, type: 'INSUMO' },
  { id: 'otr-26', category: 'OTROS DISPOSITIVOS', name: 'Atril', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'otr-27', category: 'OTROS DISPOSITIVOS', name: 'Silla de Ruedas Con 2 Cinturores', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'otr-28', category: 'OTROS DISPOSITIVOS', name: 'Pato', requiredStock: 1, type: 'INSUMO' },
  { id: 'otr-29', category: 'OTROS DISPOSITIVOS', name: 'Piscingo', requiredStock: 1, type: 'INSUMO' },
  { id: 'otr-30', category: 'OTROS DISPOSITIVOS', name: 'Riñonera', requiredStock: 1, type: 'INSUMO' },

  // TRAUMA
  { id: 'tra-1', category: 'TRAUMA', name: 'Collar Cervical Adulto', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'tra-2', category: 'TRAUMA', name: 'Collar Cervical Pediátrico', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'tra-3', category: 'TRAUMA', name: 'Collar de Estricación Graduable Adulto', requiredStock: 2, type: 'DISPOSITIVO' },
  { id: 'tra-4', category: 'TRAUMA', name: 'Collar de Estricación Graduable Pediátrico', requiredStock: 2, type: 'DISPOSITIVO' },
  { id: 'tra-5', category: 'TRAUMA', name: 'Inmovilizadores Cefálicos', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'tra-6', category: 'TRAUMA', name: 'Inmovilizadores Extremidades Cartoplast Adulto', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'tra-7', category: 'TRAUMA', name: 'Inmovilizadores Extremidades Cartoplast Pediatrico', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'tra-8', category: 'TRAUMA', name: 'Venda Elástica (Varios Tamaños)', requiredStock: 3, type: 'DISPOSITIVO' },
  { id: 'tra-9', category: 'TRAUMA', name: 'Venda de Gasa (Varios Tamaños)', requiredStock: 2, type: 'DISPOSITIVO' },
  { id: 'tra-10', category: 'TRAUMA', name: 'Venda de Algodón (Algodón Laminado)', requiredStock: 3, type: 'DISPOSITIVO' },
  { id: 'tra-11', category: 'TRAUMA', name: 'Venda Triangular', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'tra-12', category: 'TRAUMA', name: 'Compresa Esteril y/o Tela', requiredStock: 2, type: 'DISPOSITIVO' },
  { id: 'tra-13', category: 'TRAUMA', name: 'Aposito de Gasa y Vendaje de tela', requiredStock: 2, type: 'DISPOSITIVO' },

  // ASEO
  { id: 'ase-1', category: 'ASEO', name: 'Detergente y desinfectante (Benziral)', requiredStock: 1, type: 'INSUMO' },
  { id: 'ase-2', category: 'ASEO', name: 'Eucida Advance', requiredStock: 1, type: 'INSUMO' },
  { id: 'ase-3', category: 'ASEO', name: 'Escoba', requiredStock: 1, type: 'INSUMO' },
  { id: 'ase-4', category: 'ASEO', name: 'Trapero', requiredStock: 1, type: 'INSUMO' },
  { id: 'ase-5', category: 'ASEO', name: 'Balde', requiredStock: 1, type: 'INSUMO' },
  { id: 'ase-6', category: 'ASEO', name: 'Bolsas Rojas (Patógenos)', requiredStock: 3, type: 'INSUMO' },
  { id: 'ase-7', category: 'ASEO', name: 'Bolsas Negras (Ordinarios)', requiredStock: 3, type: 'INSUMO' },
  { id: 'ase-8', category: 'ASEO', name: 'Delantal Plástico', requiredStock: 1, type: 'INSUMO' },
  { id: 'ase-9', category: 'ASEO', name: 'Guantes de Caucho', requiredStock: 1, type: 'INSUMO' },

  // EQUIPOS BIOMEDICOS
  { id: 'bio-1', category: 'EQUIPOS BIOMEDICOS', name: 'Monitor de Signos Vitales', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'bio-2', category: 'EQUIPOS BIOMEDICOS', name: 'Brazalete Adulto Monitor', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'bio-3', category: 'EQUIPOS BIOMEDICOS', name: 'Brazalete Pediatrico Monitor', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'bio-4', category: 'EQUIPOS BIOMEDICOS', name: 'Oximetro de Pulso Monitor Adulto', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'bio-5', category: 'EQUIPOS BIOMEDICOS', name: 'Oximetro de Pulso Monitor Pediatrico', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'bio-6', category: 'EQUIPOS BIOMEDICOS', name: 'Oximetro de Pulso Portable', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'bio-7', category: 'EQUIPOS BIOMEDICOS', name: 'Tensiómetro Adulto', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'bio-8', category: 'EQUIPOS BIOMEDICOS', name: 'Tensiómetro Pediátrico', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'bio-9', category: 'EQUIPOS BIOMEDICOS', name: 'Fonendoscopio Adulto', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'bio-10', category: 'EQUIPOS BIOMEDICOS', name: 'Fonendoscopio Pediátrico', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'bio-11', category: 'EQUIPOS BIOMEDICOS', name: 'Termómetro Clínico', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'bio-12', category: 'EQUIPOS BIOMEDICOS', name: 'Linterna reflejo pupilar', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'bio-13', category: 'EQUIPOS BIOMEDICOS', name: 'Baterias de Respaldo Linterna', requiredStock: 'par', type: 'INSUMO' },
  { id: 'bio-14', category: 'EQUIPOS BIOMEDICOS', name: 'Aspirador de Secreciones Eléctrico', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'bio-15', category: 'EQUIPOS BIOMEDICOS', name: 'Glucometro con tirillas y baterias', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'bio-16', category: 'EQUIPOS BIOMEDICOS', name: 'Termohidrometro de Pared', requiredStock: 1, type: 'DISPOSITIVO' },

  // KIT DE DERRAMES (PARA FLUIDOS CORPORALES)
  { id: 'der-1', category: 'KIT DE DERRAMES (PARA FLUIDOS CORPORALES)', name: 'Guantes de caucho', requiredStock: '1 par', type: 'INSUMO' },
  { id: 'der-2', category: 'KIT DE DERRAMES (PARA FLUIDOS CORPORALES)', name: 'Gel solidificante de fluidos', requiredStock: 1, type: 'INSUMO' },
  { id: 'der-3', category: 'KIT DE DERRAMES (PARA FLUIDOS CORPORALES)', name: 'Escobilla', requiredStock: 1, type: 'INSUMO' },
  { id: 'der-4', category: 'KIT DE DERRAMES (PARA FLUIDOS CORPORALES)', name: 'Recogedor', requiredStock: 1, type: 'INSUMO' },
  { id: 'der-5', category: 'KIT DE DERRAMES (PARA FLUIDOS CORPORALES)', name: 'Toallas de papel', requiredStock: 2, type: 'INSUMO' },
  { id: 'der-6', category: 'KIT DE DERRAMES (PARA FLUIDOS CORPORALES)', name: 'Bolsas Rojas (Patógenos)', requiredStock: 2, type: 'INSUMO' },
  { id: 'der-7', category: 'KIT DE DERRAMES (PARA FLUIDOS CORPORALES)', name: 'Precillas de Seguridad para sellar bolsas', requiredStock: 2, type: 'INSUMO' },
  { id: 'der-8', category: 'KIT DE DERRAMES (PARA FLUIDOS CORPORALES)', name: 'monogafas para protección', requiredStock: 1, type: 'INSUMO' },
  { id: 'der-9', category: 'KIT DE DERRAMES (PARA FLUIDOS CORPORALES)', name: 'Jeringa de 50 ml', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'der-10', category: 'KIT DE DERRAMES (PARA FLUIDOS CORPORALES)', name: 'Tapabocas', requiredStock: 2, type: 'INSUMO' },

  // KIT DE ATAQUE POR AGENTES QUIMICOS
  { id: 'qui-1', category: 'KIT DE ATAQUE POR AGENTES QUIMICOS', name: 'Lactatos de Ringer x 500 ml', requiredStock: 4, type: 'MEDICAMENTO' },
  { id: 'qui-2', category: 'KIT DE ATAQUE POR AGENTES QUIMICOS', name: 'Botellon de agua potable x 5 Litros', requiredStock: 2, type: 'INSUMO' },
  { id: 'qui-3', category: 'KIT DE ATAQUE POR AGENTES QUIMICOS', name: 'Frasco de Tirillas de reacción de PH', requiredStock: 1, type: 'REACTIVO' },
  { id: 'qui-4', category: 'KIT DE ATAQUE POR AGENTES QUIMICOS', name: 'Guantes de Nitrilo para manejo de quimicos (Par)', requiredStock: 2, type: 'INSUMO' },
  { id: 'qui-5', category: 'KIT DE ATAQUE POR AGENTES QUIMICOS', name: 'Clorhexidina por 120 ml', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'qui-6', category: 'KIT DE ATAQUE POR AGENTES QUIMICOS', name: 'Gorros quirurjicos', requiredStock: 2, type: 'INSUMO' },
  { id: 'qui-7', category: 'KIT DE ATAQUE POR AGENTES QUIMICOS', name: 'Batas', requiredStock: 2, type: 'INSUMO' },
  { id: 'qui-8', category: 'KIT DE ATAQUE POR AGENTES QUIMICOS', name: 'Papel Craft pliego', requiredStock: 1, type: 'INSUMO' },
  { id: 'qui-9', category: 'KIT DE ATAQUE POR AGENTES QUIMICOS', name: 'Toallas de papel', requiredStock: 1, type: 'INSUMO' },
  { id: 'qui-10', category: 'KIT DE ATAQUE POR AGENTES QUIMICOS', name: 'Rotulos de Marcación', requiredStock: 1, type: 'INSUMO' },
  { id: 'qui-11', category: 'KIT DE ATAQUE POR AGENTES QUIMICOS', name: 'Sobre de papel oficio', requiredStock: 1, type: 'INSUMO' },
  { id: 'qui-12', category: 'KIT DE ATAQUE POR AGENTES QUIMICOS', name: 'Sobre de papel carta', requiredStock: 1, type: 'INSUMO' },
  { id: 'qui-13', category: 'KIT DE ATAQUE POR AGENTES QUIMICOS', name: 'Bolsa ziploc varios tamaños', requiredStock: 3, type: 'INSUMO' },
  { id: 'qui-14', category: 'KIT DE ATAQUE POR AGENTES QUIMICOS', name: 'Caiman para recoger cabello', requiredStock: 1, type: 'INSUMO' },
  { id: 'qui-15', category: 'KIT DE ATAQUE POR AGENTES QUIMICOS', name: 'Tijera de papel', requiredStock: 1, type: 'INSUMO' },
  { id: 'qui-16', category: 'KIT DE ATAQUE POR AGENTES QUIMICOS', name: 'Monogafas de protección', requiredStock: 2, type: 'INSUMO' },
  { id: 'qui-17', category: 'KIT DE ATAQUE POR AGENTES QUIMICOS', name: 'Marcador negro permanente', requiredStock: 1, type: 'INSUMO' },
  { id: 'qui-18', category: 'KIT DE ATAQUE POR AGENTES QUIMICOS', name: 'Bolsas Negra', requiredStock: 2, type: 'INSUMO' },

  // KIT ATENCIÓN DE PARTOS
  { id: 'par-1', category: 'KIT ATENCIÓN DE PARTOS', name: 'Pinza de Maguil (estéril)', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'par-2', category: 'KIT ATENCIÓN DE PARTOS', name: 'Pinza Rochester (estéril)', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'par-3', category: 'KIT ATENCIÓN DE PARTOS', name: 'Clip Umbilical', requiredStock: 2, type: 'INSUMO' },
  { id: 'par-4', category: 'KIT ATENCIÓN DE PARTOS', name: 'Batas desechables', requiredStock: 2, type: 'INSUMO' },
  { id: 'par-5', category: 'KIT ATENCIÓN DE PARTOS', name: 'Tijeras de material (estéril)', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'par-6', category: 'KIT ATENCIÓN DE PARTOS', name: 'Pañal para bebe etapa 0', requiredStock: 2, type: 'INSUMO' },
  { id: 'par-7', category: 'KIT ATENCIÓN DE PARTOS', name: 'Pañal Adulto', requiredStock: 1, type: 'INSUMO' },
  { id: 'par-8', category: 'KIT ATENCIÓN DE PARTOS', name: 'Par de Guantes Quirurgicos', requiredStock: 2, type: 'INSUMO' },
  { id: 'par-9', category: 'KIT ATENCIÓN DE PARTOS', name: 'Gasas Esteril Pre-cortada', requiredStock: 1, type: 'DISPOSITIVO' },
  { id: 'par-10', category: 'KIT ATENCIÓN DE PARTOS', name: 'Perilla de Succión', requiredStock: 1, type: 'INSUMO' }
];
